services:
  yolo:
    build: .
    container_name: yolo
    working_dir: /workspace
    shm_size: '8gb'
    ipc: host
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    gpus: all